### ISSUE TITLE
Add ability to extend existing projects

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-vscode-extensions#19]
Add Grid, Form or Chart to an existing project. The workflow would be the following:

1. User works inside VsCode on KendoAngular/React Project
2. We have the extension available in the taskbar (like this)
![image](https://user-images.githubusercontent.com/598514/70337964-b323aa80-1854-11ea-91af-aaa51b0ed887.png)
3. Upon open of the extension you can select add new component (grid|chart|form) -> type of component -> bind

**Comment by panayot-cankov** [comment]
https://github.com/telerik/vscode-extensions/issues/23
