### ISSUE TITLE
Generated project has two levels of nested folders

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-vscode-extensions#20]
Currently when you generate a project there are two levels of folders with the project name. This seems to be the logic in the CoreTemplateStudio dlls and can not be handled by parameters. Similar issue is logged for [WebTemplateStudio](https://github.com/microsoft/WebTemplateStudio/issues/686).  The questions which we should answer before making any changes are.

1. Should we make this nesting with parameters, in other words make this conditional(maybe expose something in the UI of the extension to enable this)?
2. Should we just modify our CoreTemplateStudio forked dlls to trim the exces level?

@eeasss @vvatkov

**Comment by eeasss** [comment]
1. I think probably no. It doesn't really seem very useful to create new folder inside the workspace folder you first chose. I don't know why MS decided to proceed this way.
2. Yes, let's change that there. @vvatkov what do you think?

**Comment by vvatkov** [comment]
It is a .Net approach to have a common folder that contains multiple folders with projects. Let say we have an unit tests project next to that projects with the actual application. Does this make sense in our case?

**Comment by vvatkov** [comment]
With @eeasss we have agreed that we should have the flexibility to have nested folders. However, we are going to remove the redundant folder for the current projects and make a configuration driven logic in the API which will allow having a nested folder or not.

**Comment by panayot-cankov** [comment]
https://github.com/telerik/vscode-extensions/issues/22
