### ISSUE TITLE
Add Blazor project generation

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-vscode-extensions#41]
Related issue - https://github.com/telerik/kendo-ux-private/issues/110

**Comment by eeasss** [comment]
Release prerequisites: 
- [ ] Readme for the visual studio extensions gallery 
- [ ] Mention in the docs (either getting started or specific extensions section)
- [ ] EULA for the extension + Entry in the 3rd party dependencies library.

**Comment by ag-petrov** [comment]
Working branch - https://github.com/telerik/kendo-vscode-extensions/tree/blazor-scaffolder

**Comment by ag-petrov** [comment]
When discussing things with @marin-bratanov the question about what nuget package should be referenced arouse. Should we use a trial or a commercial nuget? Is there a way we can know whether the user building the project is a licensed user and according to that put a commercial nuget? 

@eeasss , @veselints , @momchilstefanov , @mariaveledinova  any thoughts?

**Comment by marin-bratanov** [comment]
If we can't do it programmatically (we can do it in the Visual Studio extensions), perhaps we can add it as a step (question) for the user what license they want to target. Not ideal, but could be workable

**Comment by eeasss** [comment]
Integration with the licensing system is something on the very distant radar, but at this moment it is unrealistic to go that way. This means we have no way to know whether the user has any license or not. 

Marin's proposal is a valid one, however, it is sort of  mechanism for bypassing the protections we have established with the downloads system and the trial watermark.

I believe that the safest best for the first version is to go with the trial versions, and may be mention in the readme that the nugets can easily be replaced in case you have license.

**Comment by marin-bratanov** [comment]
If they don't have a commercial license and they choose to create a project with it - they won't be able to restore the package and the build will fail. Unless our nuget feed fails, they cannot obtain our commercial packages.

**Comment by eeasss** [comment]
Ok this makes sense, I didn't realize we only add references to the project.

**Comment by momchilstefanov** [comment]
We think we can add communication with the licensing services relatively easy in the CoreTemplateStudio once we get to this. So you'll just need to add a step in the UI which collects username and password and the CoreTemplateStudio will then provide the license the user has and the latest available version of the Blazor.

**Comment by marin-bratanov** [comment]
We have the nuget package references, and two paths to the assets (JS and CSS) differ based on the license (the package name).

**Comment by ag-petrov** [comment]
Generally I am almost ready, you can see the current state in this branch - https://github.com/telerik/kendo-vscode-extensions/tree/blazor-scaffolder . What is left is to change the Kendoka with the Blazor Ninja. I have referenced the Trial version in the package for now. Tested the generation works like a charm.

Two things are left outstanding
1. Will we try to integrate the licensing services for the first release? Here we will need design on where this form for the cridentials will be shown and how it should look.
2. In the current version of the Blazor generation we have not added a blank page. As we discussed with @marin-bratanov it seems redundant. Should I add such a page?

Any comments are welcomed.

**Comment by eeasss** [comment]
@ag-petrov the purpose of blank page is just a convenience, if you want to have an empty playground, with the required references registered. I think it's up to the blazor team to decide if they want to add one.

**Comment by marin-bratanov** [comment]
The Telerik references are added at the project level, so we don't need an explicit page, IMO

**Comment by eeasss** [comment]
Great, you can choose not to add it then, your take.

**Comment by mariaveledinova** [comment]
Hey everyone, 
why don't we replicate the same journey in VS Code as the one from Visual Studio. When creating a project with VS extensions it is prompting for email/ pass of Telerik account and it is able to determine your license type (trial/dev).
![image](https://user-images.githubusercontent.com/51785330/75359546-39ccae80-58bd-11ea-8d3a-07e0a4001b65.png)

I am afraid it is too limiting if we have VS Code extention just for trialists and for licensed customers to have manual work to make it work.
 
Momchi can we not have the same in VS Code @momchilstefanov ?

**Comment by eeasss** [comment]
@mariaveledinova it is not possible to replicate the same experience (technical limitations in the way nuget are suppored by Visual Studio and the support, or lack of such, in VsCode. Also the UX is in this case).  

The best option right now seems to be what @marin-bratanov proposed few posts above. Ask people to chose whether they want trial/paid. If they chose paid we assume that they have setup the needed authentication in the CLI they use to restore the products.

**Comment by ag-petrov** [comment]
@eeasss will the proposition by @marin-bratanov  be implemented and do we need design from @tyanko ?

**Comment by eeasss** [comment]
@ag-petrov, yes, and we most probably don't need design. We can trial / paid license option here, using the same layout. Probably the only thing we need are appropriate icons. What do you think?
![image](https://user-images.githubusercontent.com/598514/76087579-20171f80-5fbf-11ea-92eb-76a1bac5577d.png)

**Comment by ag-petrov** [comment]
Guys I am ready, I have updated the projects using the new mascots and you can test the app. 

#### Prerequisites
One should have a newever version of node(I have 12.14.1) and yarn installed

#### Testing things

1. If testing on windows copy the content from \\vvivanovlap\share\vscode api\publish-x86 and replace the one in blazor-ui-template-wizard\src\extension\src\api\win32.
2. Open the blazor-ui-template-wizard folder
3. Open bash in that folder and execute 'sh build'
4. Open blazor-ui-template-wizard\src\extension with VS Code and hit F5
5. Press ctrl+shift+p and type Blazor and you will see our extension, click on it
6. Follow the precedures in the extension

After the applications are create you can open and test them. For that purpose you should have [blazor ](https://dotnet.microsoft.com/download/dotnet-core/3.1) installed.

Our projects use the latest version of the packages like [here](https://github.com/telerik/kendo-vscode-extensions/blob/blazor-scaffolder/blazor-ui-template-wizard/templates/Web/Projects/BlazorServerDefault/ServerApp.csproj#L9) and
[here](https://github.com/telerik/kendo-vscode-extensions/blob/blazor-scaffolder/blazor-ui-template-wizard/templates/Web/Projects/BlazorClientDefault/Client/ClientApp.Client.csproj#L15) and I am not sure whether we should to this or rather specify
a version as the other references have a [specific version](https://github.com/telerik/kendo-vscode-extensions/blob/blazor-scaffolder/blazor-ui-template-wizard/templates/Web/Projects/BlazorClientDefault/Client/ClientApp.Client.csproj#L11-L14) 

@eeasss @vvatkov @marin-bratanov any comments are welcome

**Comment by vvatkov** [comment]
Great job! I just want to mention that the latest extension can be found here \\filesrvbg01.telerik.com\Distributions\DailyBuilds\Guidance\VSCodeExtensions\blazor-scaffolder

**Comment by ag-petrov** [comment]
One additional note, the projects inside the extension are configured to target the future 2.9.0 release of Telerik UI for Blazor this means that we should release after them(and the mascot is not shown anywhere yet).

**Comment by momchilstefanov** [comment]
I also want to jump in to remind you that we will need some marketing information for the Visual Studio Marketplace when we upload the extension there. You could check the Kendo UI Template Wizard page to see what kind of texts, links and pictures are used and also what kind of tags we should associate with the extension.

**Comment by marin-bratanov** [comment]
We need to remove the KendoUI branding - from the name, the subtitle and the image. I am also unsure whether we need/can keep the current issue tracker.

![Extension_ Telerik UI for Blazor Template Wizard - needed changes](https://user-images.githubusercontent.com/5746515/76614223-522d0200-6528-11ea-868f-62f1935cd367.png)


Here is a sample text for the `Features` section

```
The `Telerik UI for Blazor Template Wizard` lets you create [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor) projects that use the [Telerik UI for Blazor components](https://www.telerik.com/blazor-ui). 

You can create both WASM and Server-side projects, and it also contains a few predefined examples (a grid with CRUD operations through a service, charts, forms) that you can review and use as base for further development.
```

**Comment by eeasss** [comment]
@marin-bratanov  good call. May be link to the blazor feedback portal. We plan to link to kendo feedback portals as well in a future moment.

**Comment by ag-petrov** [comment]
@eeasss will do my best to replace things today. I will ask for the logo as I do not have an exact match for that one.

**Comment by marin-bratanov** [comment]
To an extent, it will be better to keep the issues for the extension in a repo for the extension, perhaps we can add labels for the technology it is about so we can filter/sort the issues? If this will not work for you, let's direct them to the Blazor Feedback Portal.

Docs are half-done at http://kendobuild-staging.dev.progress.com/blazor-ui/getting-started/vs-code-integration/introduction

We need the following:
* to use a different publisher, not Kendo UI. I am not sure we can use Progress, though, but there is already Telerik with some NativeScript extension so we should be able to use it
* a new icon (perhaps a crop of the current ninja mascot from the descriptions in the extension?)
* determine the URL at which the extension will be available in the marketplace so I can link it from the docs
* have it live so I can screenshot installation steps. I think we can let it go live on Monday or Tuesday, a few days before our official release so I can do this and we can test if all works well. The major dependency that requires 2.9.0 is that we no longer disable the linker, but this is kind of fixed in the latest WASM Preview from MS, so these project templates will work reasonably well with the current 2.8.0 too

**Comment by momchilstefanov** [comment]
I think we can upload it through the Telerik publisher we use for the VS for Windows extension. Note that it's not the same Telerik publisher used by the NativeScript extension. :)

**Comment by marin-bratanov** [comment]
I have merged the templates into master https://github.com/telerik/kendo-vsx-templates/pull/15

because it was causing issues and discrepancies in the VS extensions. The old branch is now deleted

**Comment by ag-petrov** [comment]
Guys, I have corrected the problems on the image that @marin-bratanov shared. It should be fine you can check it once the build produces the extension. Only the feedback portal was not altered as I was not sure whether the Blazor portal or the current link should stay. If it should be replaced one can commit the change in [this ](https://github.com/telerik/kendo-vscode-extensions/blob/blazor-scaffolder/blazor-ui-template-wizard/src/extension/README.md)file.

**Comment by vvatkov** [comment]
There is a successful build here \filesrvbg01.telerik.com\Distributions\DailyBuilds\Guidance\VSCodeExtensions\blazor-scaffolder

**Comment by vvatkov** [comment]
Guys, the validation from our side is finished. We've tested:

- the dev/trial functionality
- the Callhome events and metrics
- the overall functionality when both Blazor and Kendo VSCode extensions are installed 

Please, let me know how do we proceed and when we should publish the extension.

**Comment by marin-bratanov** [comment]
From the early posts in this thread, it seems that an EULA is missing. If we already have it, I say we can go live today, so I can write docs for the installation process and actual URL, so we can have all of that for tomorrow's release.

**Comment by vvatkov** [comment]
Guys, we've just released Telerik UI for Blazor Template Wizard. It is now available in the marketplace.

https://marketplace.visualstudio.com/items?itemName=TelerikInc.blazortemplatewizard

**Comment by marin-bratanov** [comment]
We also have docs that will go live with our release tomorrow, preview [here](http://kendobuild-staging.dev.progress.com/blazor-ui/getting-started/vs-code-integration/introduction)
