### ISSUE TITLE
Add default values for project details in New project page

### ISSUE THREAD

**Issue by YanaTacheva** [telerik/kendo-vscode-extensions#42]
Adding default values for **Project Name** and **Output Path** will improve the project creation usability. Currently, the above-mentioned fields are empty and they should be filled everytime the user is creating a Telerik application. 

![auto-fill-values-for-project-info](https://user-images.githubusercontent.com/17295287/75550562-d49ec780-5a3a-11ea-884c-a2e12b6e41b7.png)

As a comparison, Microsoft web template studio extension supports auto-filled project information values and creating a project is far more facilitated.

![microsoft-new-project](https://user-images.githubusercontent.com/17295287/75550768-46771100-5a3b-11ea-95f5-e417ab80649d.png)

**Comment by panayot-cankov** [comment]
https://github.com/telerik/vscode-extensions/issues/21
