### ISSUE TITLE
Add Form Builder Screen

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-vscode-extensions#5]
Form Builder screen that allows for generation of an edit form with all the needed editors (kendoreact or kendoangular components). 

We provide json schema or a sample dataitem and the builder reads or infers the needed editors. 

For react this will output the kendoreact form with kendoreact inputs, and for angular this will output the default angular form with our inputs.

**Comment by panayot-cankov** [comment]
https://github.com/telerik/vscode-extensions/issues/19
