### ISSUE TITLE
Automate release 

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-vscode-extensions#63]
Release automation should follow the established practices we have from angular and react.

- [x] Master should get locked 
- [x] We should add new build on the VSX Machine that runs the vscode extensions build called `release develop as master` whose purpose would be to rebase all work from develop to master 
- [x] Split extensions into two repositories - kendo-vscode-extensions and blazor-vscode-extensions with setup for separate builds and release notes automation.
- [x] Release automation should be build  based on the above and construct appropriate change log based on the commit messages since the previous release. 
- [x] Release notes should be posted to gitbub releases both for kendo-vscode-extensions and blazor-vscode-extensions

@ipeshev can help with details how this setup works on the kendo jenkins. @PetiaVladova

**Comment by ipeshev** [comment]
We will use semantic-release without publishing phase , only tag generation.

**Comment by ipeshev** [comment]
In the end plugin is used to publish in marketplace - [code here](https://github.com/telerik/blazor-vscode-extensions/pull/6).

**Comment by ipeshev** [comment]
Will have short offline discussion with VSX team to discuss the progress.

**Comment by ipeshev** [comment]
With current semantic-release@17.0.2 we do not have possibility to have custom version format, there are some push for this feature from other semantic-release users https://github.com/semantic-release/semantic-release/issues/1582 but the maintainers look really rigid regarding foreign PRs.

**Comment by eeasss** [comment]
Any updates about this issue?

**Comment by ipeshev** [comment]
Yes it is almost done for blazor( for the other extension it will be far easier), waiting for VSX team to confirm one last check.

**Comment by ipeshev** [comment]
The seed has spread to ASP.NET Core VS Code extension, it up coming for Kendo.
