### ISSUE TITLE
Revise the way ComponentUsed is reported in Angular/React

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-vscode-extensions#82]
During testing we have found a couple of problems:

- [ ] 1) Detection use for React uses detection for Kendo UI for React Wrappers instead of looking for KendoReact Components. Fix is already committed and patch for the extension is pending. 
- [ ] 2) The way ComponentUsed is reported for Angular is likely sub-optimal. Right now we look for the imports used on the page currently being edited, whereas in Angular it is common to put global imports in the app.modules file. This is likely leading to partial reporting of events. Also, names of reported components are incomplete and don't observe the mapping the are using for the Kendo UI reports (kendo.ui.Grid etc)
- [ ] 3) There is an issue with the amount of LicenseUsage events reported for Angular. Current hypothesis points that because of 2) we rarely report ComponentUsed for Angular and hence fail to report LicenseUsage, since it is attached to the first ComponentUsed for the day. Alternative explanation could be that an issue with Cache and IsolatedStorage, where first detected ComponentUsage will submit LicenseUsage event no matter what is the product, and after that the event will be cached for the current date. This behavior is likely to be resolved when we implement https://github.com/telerik/CoreTemplateStudio/issues/9

//cc @vvatkov, @momchilstefanov  for comments if the above doesn't cover the whole picture.

**Comment by ipeshev** [comment]
One possible way to detect problems it to measure new plugin downloads vs events rise ratio ( differential )

**Comment by panayot-cankov** [comment]
https://github.com/telerik/vscode-extensions/issues/20
